---
functional: |
  Интерфейс интернет-магазина по продаже товаров должен иметь каталог
  со списком товаров.  
  Возможность перехода на следующую и предыдущую страницу
  каталога.  
  Возможность фильтрации и поиска товара. Возможность перехода в
  карточку товара.
  Возможность перехода в форму регистрации нового пользователя.   
  Возможность перехода в форму авторизации существующего пользователя.  
  Возможность перехода в корзину.  
  Возможность перехода в список заказов только для авторизованного 
  пользователя. 
  Возможность выбора русского или английского языка отображения текста. 
  Пользователь может просматривать полный список товаров в каталоге.  
  Пользователь может фильтровать товар и просматривать отфильтрованный 
  товар в каталоге.
  Пользователь может искать товары по ключевому слову.
  Пользователь может выбирать определенную категорию товара из 
  выпадающего списка.  
  Пользователь может выбирать все категории товара одновременно с 
  помощью соответствующего значения в выпадающем списке. 
  В зависимости от выбранной категории должна быть фильтрация товара 
  по бренду. 
  Независимо от выбранной категории должна быть фильтрация товара 
  по цене, цвету, размеру и наличию. 
  Пользователь может одновременно искать товары по ключевому слову и 
  включать фильтрацию.
  В миниатюре товара отображается название, описание, рейтинг, цена со 
  скидкой и без скидки.  
  Пользователь может вернуться обратно в каталог из корзины или списка 
  заказов или карточки товара. 
  Отображается название товара, его рейтинг, цена со скидкой и цена без 
  скидки.  
  Пользователь может добавить товар в корзину в нужном количестве. 
  Пользователь может перейти в отфильтрованный каталог для просмотра 
  других товаров аналогичной категории. 
  Пользователь может изменить количество товара или удалить товар из 
  корзины. 
  Пользователь может авторизоваться и посмотреть заказ. 
  Пользователь может авторизоваться и оформить заказ с переходом на 
  страницу оплаты. 
  Пользователь может авторизоваться и просмотреть список ранее сделанных 
  им заказов.
non-functional: |
  Должна быть разработана веб-версия сайта в виде SPA без перезагрузки 
  страницы.
  Должна быть разработана мобильная версия сайта.
  Сайт должен иметь адаптивную верстку при просмотре веб-страницы на 
  компьютерах и на мобильных устройствах. 
  В подвале сайта должна быть предусмотрена кнопка для перехода на 
  мобильную версию сайта и обратно. 
  Размеры кнопок, расположение элементов в формах и дизайн должны 
  сохраняться при переключении  языка текста с русского на английский.
  Сайт должен содержать шапку с основным меню, тело с меню фильтрации и
  поиска, подвал c кнопкой перехода в режим просмотра веб версии и 
  мобильной версии.
  Веб-версия и мобильная версия сайта должны быть выполнены в едином 
  стиле. 
  implicit: |
  При отсутствии соединения с сетью интернет должно отображаться стандартное 
  текстовое сообщение браузера об отсутствии подключения.  
  Протокол передачи данных HTTP должен поддерживать расширения 
  шифрования SSL/TLS.  
  Должен быть реализован механизм управления сессиями Cookies.  
  В сессии браузера должна храниться информация о корзине, сделанных 
  заказах и данные учетной записи пользователя.
  Поиск товаров должен быть нечувствителен к регистру символов.
  Поля авторизации, регистрации и выбора цены товара в каталоге должны 
  валидировать данные, вводимые пользователем.
