---
functional: >
  - Интерфейс интернет-магазина по продаже товаров должен иметь
  основные функции: |
      Каталог со списком товаров. 
      Возможность фильтрации и поиска товара.
      Возможность перехода в карточку товара.  
      Возможность перехода в форму регистрации нового пользователя.  
      Возможность перехода в форму авторизации существующего пользователя.  
      Возможность перехода в корзину. 
      Возможность перехода в список заказов (только для авторизованного пользователя).
      Возможность выбора русского или английского языка отображения текста. 
  - В каталоге товаров: |
      Пользователь может просматривать полный список товаров в каталоге. 
      Пользователь может фильтровать товар и просматривать отфильтрованный товар в каталоге.
      Пользователь может искать товары по ключевому слову.     
      Пользователь может выбирать определенный тип (категорию) товара из выпадающего списка. 
      Пользователь может выбирать все типы (категории) товара одновременно с помощью соответствующего значения в выпадающем списке.
      В зависимости от выбранного типа (категории) должна быть фильтрация товара по бренду.
      Независимо от выбранного типа (категории) должна быть фильтрация товара по цене, цвету, размеру и наличию.
      Пользователь может одновременно искать товары по ключевому слову и включать фильтрацию. 
      В миниатюре товара отображается название, описание, рейтинг, цена со скидкой и без скидки. 
      Пользователь может вернуться обратно в каталог из корзины или списка заказов или карточки товара.
  - В карточке товара: |
      Отображается название товара, его рейтинг, цена со скидкой и цена без скидки. 
      Пользователь может добавить товар в корзину в нужном количестве.
  - На странице корзины: |
      Пользователь может изменить количество товара или удалить товар из корзины.
      Пользователь может посмотреть заказ(только для авторизованного пользователя).
      Пользователь может оформить заказ с переходом на страницу оплаты (только для авторизованного пользователя).
      Пользователь может просмотреть список ранее сделанных им заказов (только для авторизованного пользователя).
non-functional: >
  - Требования к разработке страниц: |
      Должна быть разработана веб-версия сайта в виде SPA без перезагрузки страницы.
      Должна быть разработана мобильная версия сайта.
  - Требования Адаптивности: |
      Сайт должен иметь адаптивную верстку при просмотре веб-страницы на компьютерах и на мобильных устройствах. 
      В подвале сайта должна быть предусмотрена кнопка для перехода на мобильную версию сайта и обратно. 
      Размеры кнопок, отступы и расположение форм не должны меняться при переключении  языка текста с русского на английский и обратно.
  - Требования Usability: |
      Требования Usability учитываются на этапе Дизайна и Разработки, и обеспечиваются на этапе технической поддержки на основании метрик Google Analytic.
  - Требования к дизайну и стилям: |
      - Сайт должен содержать: |
         шапку с основным меню, 
         тело с меню фильтрации и поиска, 
         подвал c кнопкой перехода в режим просмотра веб верстки или мобильной верстки.
      Веб-версия и мобильная версия сайта должны быть выполнены в едином стиле.
      Внешний вид страницы, включая цветовое оформление сайта и характеристики текстовых шрифтов определяются на этапе Дизайна..  
  - Требования к скорости работы: |
      Скорость работы сайта должна быть оптимизирована для типа соединения Wi-Fi.
      При низкой скорости подключения (3G, 4G) страница должна в первую очередь отображать текст, затем настройки стилей, затем изображения и видео.
  - Требования производительности: | 
      Сайт должен быдерживать нагрузку в среднем 20 ответов сервера в секунду. 
      API платежных и прочих смежных систем должны обеспечивать не более 20 ответов сервера.
  - Требования безопасности: |
      Сайт должен быть устойчив к SQL-инъекциям и XSS атакам.
      Пользователь не может посмотреть чужой заказ по номеру id в URL ссылке.
  - Требования совместимости: |
      Сайт должен быть совместимым с последними, на момент тестирования, версиями браузеров Google Chrome, Safari, Opera, Firefox и Explorer.
  - Требования локализации: |
      Должна быть предусмотрена мультиязычность с возможностью выбора в меню вариантов отображения текста на русском или английском языке.
  - Требования к конфигурации: |
      Сайт должен открываться на операционных системах Windows, IOS и Аndroid.
implicit: >
  - Специальные требования: |
      При отсутствии соединения с сетью интернет должно отображаться стандартное текстовое сообщение браузера об отсутствии подключения.  
      Протокол передачи данных HTTP должен поддерживать расширения шифрования SSL/TLS.  
      Должен быть реализован механизм управления сессиями Cookies.  
      В сессии браузера должна храниться информация о корзине, сделанных заказах и данные учетной записи пользователя.
      Файлы Cookies должны быть разработаны с учетом ФЗ «О персональных данных».
      Поиск товаров должен быть нечувствителен к регистру символов.
